services:
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: langgraph
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  langgraph-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2048:8000"
    env_file:
      - .env
    volumes:
      - .:/deps/major
    working_dir: /deps/major
    depends_on:
      - redis
      - postgres

volumes:
  pgdata:
